# Generated by Django 4.0.2 on 2022-04-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('material', models.TextField(max_length=255)),
                ('color', models.TextField(max_length=255)),
                ('gender', models.TextField(max_length=255)),
                ('size', models.TextField(max_length=255)),
                ('name', models.TextField(max_length=255)),
                ('season', models.TextField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesBrand',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('createAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesStats',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.TextField()),
                ('quantity', models.IntegerField()),
                ('importPrice', models.FloatField()),
                ('quantityLeft', models.IntegerField()),
                ('createAt', models.DateField()),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothesBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothesbrand'),
        ),
    ]
