# Generated by Django 4.0.2 on 2022-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
