# Generated by Django 4.0.2 on 2022-04-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('material', models.TextField()),
                ('CPU', models.TextField()),
                ('RAM', models.TextField()),
                ('GPU', models.TextField()),
                ('OS', models.TextField()),
                ('screenSize', models.FloatField()),
                ('storage', models.TextField()),
                ('battery', models.TextField()),
                ('weight', models.FloatField()),
                ('warrantyPeriod', models.TextField()),
                ('touchID', models.TextField()),
                ('sims', models.TextField()),
                ('frontCamera', models.TextField()),
                ('rearCamera', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneBrand',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('createAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneStats',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.TextField()),
                ('quantity', models.IntegerField()),
                ('importPrice', models.FloatField()),
                ('quantityLeft', models.IntegerField()),
                ('createAt', models.DateField()),
                ('mobilePhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.mobilephone')),
            ],
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='mobilePhoneBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilephone.mobilephonebrand'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.producer'),
        ),
    ]
