# Generated by Django 4.0.2 on 2022-04-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('material', models.TextField()),
                ('CPU', models.TextField()),
                ('RAM', models.TextField()),
                ('GPU', models.TextField()),
                ('OS', models.TextField()),
                ('screenSize', models.FloatField()),
                ('storage', models.TextField()),
                ('battery', models.TextField()),
                ('weight', models.FloatField()),
                ('warrantyPeriod', models.TextField()),
                ('speaker', models.TextField()),
                ('type', models.TextField()),
                ('webCam', models.TextField()),
                ('keyborad', models.TextField()),
                ('touchID', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('createAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaptopStats',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.TextField()),
                ('quantity', models.IntegerField()),
                ('importPrice', models.FloatField()),
                ('quantityLeft', models.IntegerField()),
                ('createAt', models.DateField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptop')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptopBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptopbrand'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.producer'),
        ),
    ]
